import type { AtRule } from 'csstype';
import { round } from './round';

const toPercentString = (value: number) => `${round(value * 100)}%`;

export const toCssProperty = (property: string) =>
  property.replace(/([A-Z])/g, (property) => `-${property.toLowerCase()}`);

interface FontMetrics {
  /** Font family name as authored by font creator */
  familyName: string;
  /** The height of capital letters above the baseline */
  capHeight: number;
  /** The height of the ascenders above baseline */
  ascent: number;
  /** The descent of the descenders below baseline */
  descent: number;
  /** The amount of space included between lines */
  lineGap: number;
  /** The size of the font’s internal coordinate grid */
  unitsPerEm: number;
  /** The average width of lowercase characters (currently supports latin only) */
  xWidthAvg: number;
  // Allows full metrics interface to be passed in
  // while only type checking the required properties
  [key: string | number]: unknown;
}

interface OverrideValuesParams {
  metrics: FontMetrics;
  fallbackMetrics: FontMetrics;
}
const calculateOverrideValues = ({
  metrics,
  fallbackMetrics,
}: OverrideValuesParams): AtRule.FontFace => {
  // Calculate size adjust
  const preferredFontXAvgRatio = metrics.xWidthAvg / metrics.unitsPerEm;
  const fallbackFontXAvgRatio =
    fallbackMetrics.xWidthAvg / fallbackMetrics.unitsPerEm;

  const sizeAdjust =
    preferredFontXAvgRatio && fallbackFontXAvgRatio
      ? preferredFontXAvgRatio / fallbackFontXAvgRatio
      : 1;

  const adjustedEmSquare = metrics.unitsPerEm * sizeAdjust;

  // Calculate metric overrides for preferred font
  const ascentOverride = metrics.ascent / adjustedEmSquare;
  const descentOverride = Math.abs(metrics.descent) / adjustedEmSquare;
  const lineGapOverride = metrics.lineGap / adjustedEmSquare;

  // Conditionally populate font face properties and format to percent
  const fontFace: AtRule.FontFace = {};
  if (ascentOverride) {
    fontFace['ascentOverride'] = toPercentString(ascentOverride);
  }
  if (descentOverride) {
    fontFace['descentOverride'] = toPercentString(descentOverride);
  }
  if (lineGapOverride) {
    fontFace['lineGapOverride'] = toPercentString(lineGapOverride);
  }
  if (sizeAdjust && sizeAdjust !== 1) {
    fontFace['sizeAdjust'] = toPercentString(sizeAdjust);
  }

  return fontFace;
};

export const quoteIfNeeded = (name: string) => {
  const quotedMatch = name.match(/^['"](?<name>.*)['"]$/);
  if (quotedMatch && quotedMatch.groups?.name) {
    // Escape double quotes in middle of name
    return `"${quotedMatch.groups.name.split(`"`).join(`\"`)}"`;
  }

  if (/^"/.test(name)) {
    // Complete double quotes if incomplete and escape double quotes in middle
    const [, ...restName] = name;
    return `"${restName.map((x) => (x === `"` ? `\"` : x)).join('')}"`;
  }

  if (!/^[a-zA-Z\d\-_]+$/.test(name)) {
    // Wrap in quotes if contains any characters that are not letters,
    // numbers, hyphens or underscores
    return `"${name.split(`"`).join(`\"`)}"`;
  }

  return name;
};

type FontFace = {
  '@font-face': Omit<AtRule.FontFace, 'src' | 'fontFamily'> &
    Required<Pick<AtRule.FontFace, 'src' | 'fontFamily'>>;
};
const toCssString = (fontFaces: FontFace[]) => {
  return fontFaces
    .map(({ '@font-face': { fontFamily, src, ...restFontFaceProperties } }) => {
      const fontFace = [
        '@font-face {',
        `  font-family: ${quoteIfNeeded(fontFamily)};`,
        `  src: ${src};`,
      ];

      Object.keys(restFontFaceProperties).forEach((property) => {
        fontFace.push(
          `  ${toCssProperty(property)}: ${
            restFontFaceProperties[
              property as keyof typeof restFontFaceProperties
            ]
          };`,
        );
      });

      fontFace.push('}');

      return fontFace.join('\n');
    })
    .join('\n');
};

type AdditionalFontFaceProperties = Omit<
  AtRule.FontFace,
  | 'src'
  | 'fontFamily'
  | 'ascentOverride'
  | 'descentOverride'
  | 'lineGapOverride'
>;
type CreateFontStackOptions = {
  /**
   * Additional properties to add to the generated `@font-face` declarations.
   *
   * Accepts all valid `@font-face` properties except the following which are
   * generated by Capsize: `src`, `fontFamily`, `ascentOverride`,
   * `descentOverride`, `lineGapOverride`, although allows `size-adjust` to
   * support explicit overrides.
   */
  fontFaceProperties?: AdditionalFontFaceProperties;
};
type FontFaceFormatString = {
  /**
   * Choose between returning CSS as a string for stylesheets or `style` tags,
   * or as a style object for CSS-in-JS integration.
   *
   * Default: `styleString`
   */
  fontFaceFormat?: 'styleString';
};
type FontFaceFormatObject = {
  fontFaceFormat?: 'styleObject';
};

export function createFontStack(
  fontStackMetrics: FontMetrics[],
  options?: CreateFontStackOptions & FontFaceFormatString,
): { fontFamily: string; fontFaces: string };
export function createFontStack(
  fontStackMetrics: FontMetrics[],
  options?: CreateFontStackOptions & FontFaceFormatObject,
): { fontFamily: string; fontFaces: FontFace[] };
export function createFontStack(
  [metrics, ...fallbackMetrics]: FontMetrics[],
  optionsArg: CreateFontStackOptions = {},
) {
  const { fontFaceFormat, fontFaceProperties } = {
    fontFaceFormat: 'styleString',
    ...optionsArg,
  };
  const { familyName } = metrics;

  const fontFamilies: string[] = [quoteIfNeeded(familyName)];
  const fontFaces: FontFace[] = [];

  fallbackMetrics.forEach((fallback) => {
    const fontFamily = `${familyName} Fallback${
      fallbackMetrics.length > 1 ? `: ${fallback.familyName}` : ''
    }`;

    fontFamilies.push(quoteIfNeeded(fontFamily));
    fontFaces.push({
      '@font-face': {
        ...fontFaceProperties,
        fontFamily,
        src: `local('${fallback.familyName}')`,
        ...calculateOverrideValues({
          metrics,
          fallbackMetrics: fallback,
        }),
        ...(fontFaceProperties?.sizeAdjust
          ? { sizeAdjust: fontFaceProperties.sizeAdjust }
          : {}),
      },
    });
  });

  return {
    fontFamily: fontFamilies.join(', '),
    fontFaces: {
      styleString: toCssString(fontFaces),
      styleObject: fontFaces,
    }[fontFaceFormat],
  };
}
